server:
  port: 9081
spring:
  datasource:
    username: root
    #password: z945980051
    password: 123456
    #url: jdbc:mysql://cdb-68u6udus.cd.tencentcdb.com:10023/jiankanglaifu?characterEncoding=UTF-8&useSSL=false&serverTimezone=Hongkong
    url: jdbc:mysql://127.0.0.1:3306/jiankanglaifu?characterEncoding=UTF-8&useSSL=false&serverTimezone=Hongkong
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      #ddl-auto: create
#    show-sql: true
  servlet:
    multipart:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 15
      max-wait: -1
      max-idle: 15
      min-idle: 10