server:
  port: 9081
spring:
  datasource:
    username: root
    #password: z945980051
    password: 123456
    #url: jdbc:mysql://cdb-68u6udus.cd.tencentcdb.com:10023/jiankanglaifu?characterEncoding=UTF-8&useSSL=false&serverTimezone=Hongkong
    url: jdbc:mysql://111.230.143.197:3306/jiankanglaifu?characterEncoding=UTF-8&useSSL=false&serverTimezone=Hongkong
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      #ddl-auto: create
    #show-sql: true
  servlet:
    multipart: